//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phieuDangKi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DotThi
    {
        public string MaGV { get; set; }
        public string MaHD { get; set; }
        public Nullable<System.DateTime> Ngaythi { get; set; }
        public string Tendot { get; set; }
        public string Diachi { get; set; }
        public string Nhiemvu { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HoiDong HoiDong { get; set; }
    }
}
