//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phieuDangKi
{
    using System;
    using System.Collections.Generic;
    
    public partial class LePhi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LePhi()
        {
            this.ThiSinhs = new HashSet<ThiSinh>();
        }
    
        public string Maluachon { get; set; }
        public string Nhucau { get; set; }
        public string Trinhdo { get; set; }
        public string ThuocHV { get; set; }
        public Nullable<int> Giatien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThiSinh> ThiSinhs { get; set; }
    }
}
