//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phieuDangKi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Quan_li_thi_chung_chi_CNTTEntities : DbContext
    {
        public Quan_li_thi_chung_chi_CNTTEntities()
            : base("name=Quan_li_thi_chung_chi_CNTTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiThi> BaiThis { get; set; }
        public virtual DbSet<CapChungChi> CapChungChis { get; set; }
        public virtual DbSet<ChitietDK> ChitietDKs { get; set; }
        public virtual DbSet<DangKy> DangKies { get; set; }
        public virtual DbSet<DotThi> DotThis { get; set; }
        public virtual DbSet<GiaoVien> GiaoViens { get; set; }
        public virtual DbSet<HoiDong> HoiDongs { get; set; }
        public virtual DbSet<KetQua> KetQuas { get; set; }
        public virtual DbSet<LePhi> LePhis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThiSinh> ThiSinhs { get; set; }
        public virtual DbSet<XacNhan> XacNhans { get; set; }
    }
}
