//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phieuDangKi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThiSinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThiSinh()
        {
            this.BaiThis = new HashSet<BaiThi>();
            this.CapChungChis = new HashSet<CapChungChi>();
            this.ChitietDKs = new HashSet<ChitietDK>();
            this.XacNhans = new HashSet<XacNhan>();
        }
    
        public string SBD { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Gioitinh { get; set; }
        public string SDT { get; set; }
        public string CMT { get; set; }
        public string Maluachon { get; set; }
        public int STT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiThi> BaiThis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapChungChi> CapChungChis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChitietDK> ChitietDKs { get; set; }
        public virtual LePhi LePhi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XacNhan> XacNhans { get; set; }
    }
}
