//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_thi_cap_chu_chi_CNTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapChungChi
    {
        public string MaHD { get; set; }
        public string SBD { get; set; }
        public string Tenchungchi { get; set; }
        public Nullable<int> Sovanbang { get; set; }
        public Nullable<int> Sovaoso { get; set; }
        public Nullable<System.DateTime> Ngaycap { get; set; }
    
        public virtual HoiDong HoiDong { get; set; }
        public virtual ThiSinh ThiSinh { get; set; }
    }
}
